export const REQUEST_WEATHER_FORECAST = 'REQUEST_WEATHER_FORECAST';
export const RECEIVE_WEATHER_FORECAST = 'RECEIVE_WEATHER_FORECAST';
export const SET_SELECTED_CITY = 'SET_SELECTED_CITY';
export const SET_SELECTED_UNITS='SET_SELECTED_UNITS';
export const SHOW_HOURLY='SHOW_HOURLY';
export const SHOW_WEEKLY='SHOW_WEEKLY';
export const TOGGLE_LOADING='TOGGLE_LOADING';
